config/routes.rb
Foodholic::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_for :users
  root :to => 'home#index' 
  
  

  devise_scope :user do
    match '/user/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session, via: [:get, :delete]
  end
  
 

  
  
  scope :module => "recipe"   do
    get '/search' => 'recipes#search' , :via => :get, :as => 'search_recipes'
    post '/search' => 'recipes#search_recipes', :as => 'search_by_click'
    get '/recipes/:id/:ratings/rated_users' => 'recipes#rated_users_list', :as => 'rated_users_list' 
    get '/recipes/top_rated_recipes' => 'recipes#top_rated_recipes', :as => "top_rated_recipes"
    get '/recipes/most_rated_recipes'=> 'recipes#most_rated_recipes', :as => "most_rated_recipes"

    
    put '/recipes/approve_recipe' => 'admin_recipes#approve_recipe', :as => 'approve_recipe'
    put '/recipes/reject_recipe' => 'admin_recipes#reject_recipe', :as => "reject_recipe"
    get '/recipes/admin_pending_recipes' => 'admin_recipes#admin_pending_recipes', :as => 'admin_pending_recipes' 

    get '/recipes/new' => 'user_recipes#new',  :as => 'new_recipe'   
    post '/recipes/rate' => 'user_recipes#rate_recipe'
    get '/recipes/my_pending_recipes' => 'user_recipes#my_pending_recipes', :as => "my_pending_recipes"
    get '/recipes/my_rejected_recipes' => 'user_recipes#my_rejected_recipes', :as => "my_rejected_recipes"
    get '/recipes/my_top_rated_recipes' => 'user_recipes#my_top_rated_recipes', :as => "my_top_rated_recipes"
    get '/recipes/my_most_rated_recipes' => 'user_recipes#my_most_rated_recipes', :as => "my_most_rated_recipes"
    get '/recipes/my_approved_recipes' => 'user_recipes#my_approved_recipes', :as => "my_approved_recipes"
    get '/recipes/:id/edit' => 'user_recipes#edit' , :as => 'edit_recipe'
    put '/recipes/:id' => 'user_recipes#update'
    post '/recipes' => 'user_recipes#create'
    get '/recipes' => 'user_recipes#index'
    delete '/recipes/destroy_ingredient' => "user_recipes#destroy_ingredient"
    get '/recipes/:id' => 'recipes#show' ,:as => 'recipe'
  end
  

  get '/users/:id' => 'users#show' ,:as => 'user'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  
  put '/users/:id' => 'users#update' 
  get  'photos(.:format)' => 'photos#index', :as => :photos
  post '/photos(.:format)' => 'photos#create'
  get  '/photos/new(.:format)' => 'photos#new', :as => :new_photo
  get  '/photos/:id/edit(.:format)' => 'photos#edit', :as => :edit_photo
  get  '/photos/:id(.:format)' => 'photos#show', :as => :photo 
  put  '/photos/:id(.:format)' => 'photos#update'
  delete '/photos/:id(.:format)' => 'photos#destroy'
                            

end

app/views/common/_common_form.html.erb
<%  
  @user_set_ingredients ||=[] 


  recipe_ingredients ||= []
  ingredients_list ||=[]
  existing_ingredients =  get_existing_ingredient_array_of_hash
  recipe_ingredients =  get_recipe_ingredient_array_of_hash(@recipe) if @recipe.persisted?
  ingredients_list = recipe_ingredients if @user_set_ingredients.empty?
  ingredients_list = @user_set_ingredients if recipe_ingredients.empty?

  puts ingredients_list.inspect
  # ingredients_list = make_combo_ingredients(@user_set_ingredients, recipe_ingredients)
 %>


<%= render "/common/images_upload_modal"%>
<%= form_for(@recipe, :html => { :multipart => true , :class => 'form-horizontal'}) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation" class="control-group">
      <div class="alert alert-info">
        <ul>
          <% @recipe.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <%= print_if_notice notice %>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Recipe Name</label>
    <div class="controls">
      <input  type="hidden" name="recipe[aggregate_ratings]" value='<%=0%>'>
      <input class="span8" type="text" id="inputEmail" placeholder="reipe name" name="recipe[name]" value='<%="#{@recipe.name}"%>' required>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Discription</label>
    <div class="controls">
      <textarea id="recipe-description" class="span8" name="recipe[description]" cols="30" rows="10" value="" required>
        <%= "#{@recipe.description }"%>
      </textarea>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputEmail">serves</label>
    <div class="controls">
      <input class="span4" type="number" name="recipe[serves]" placeholder="4" required value="<%= @recipe.serves %>" required>
    </div>
  </div>  
  <div class="control-group">
    <div class="controls">
       <h5>Type and select ingredients from the list of existing ingredients</h5>
    </div>
  </div>
  <div class="control-group inline">
    <label class="control-label">Select existing ingredients</label>
    <div class="controls">
    
      <select multiple="multiple" id="existing-ingredient-list" class="chosen-select">
      <% existing_ingredients.each do |ing| %>
        <option value='<%= "#{ing['id']}-#{ing['name']}-#{ing['meal_class']}-#{ing['std_quantity']}-#{ing['calories_per_quantity']}-#{ing['std_measurement']}"%>' data-ingredient-name ="<%= "#{ing['name']}"%>" <%= selected_ingredient_for_chosen(@user_set_ingredients, recipe_ingredients, ing) %>>
          <%= ing['name'] %>
        </option>
        <% end %>
      </select>
    </div>
  </div>
 
  <div class="ingredients-container">
    <% ingredients_list.each_with_index do |ing, index| 
      if big_ingredient_container?(ing) %>
        <div class="add-ingredient" >
          <hr>
          <%= add_remove_ingredient_form_data(@recipe, ing) %>
          <div class="control-group">
            <label class="control-label" for="inputEmail" >ingredient name</label>
            <div class="controls">
              <input type="hidden"  name="ingredient[][id]" value="<%= ing['id'] %>" required>
              <input class="span8" type="text" placeholder="ingredient name" value="<%= ing['name'] %>"  name="ingredient[][name]" required>
            </div>
          </div>
          <div class="control-group inline">
            <label class="control-label" for="inputEmail">ingredient standard measurement </label>
            <div class="controls">
              <%= build_std_measurement_dropdown(:selected_true_value => ing['std_measurement'])%>
            </div>
          </div>
          <div class="control-group inline">
              <label class="control-label" for="inputEmail">ingredient meal class </label>
              <div class="controls">
                 <%= build_meal_class_dropdown(:selected_true_value => ing['meal_class'])%>
              </div>
          </div>
          <div class="control-group inline">
            <label class="control-label" for="inputEmail">ingredient standard quantity</label>
            <div class="controls">
              <input type="number" placeholder="example 10 grams" step="0.01" value="<%= ing['std_quantity'] %>" name="ingredient[][std_quantity]" required>
            </div>
          </div>
          <div class="control-group inline">
            <label class="control-label" for="inputEmail">ingredient quantity</label>
            <div class="controls">
              <input type="number" palceholder="e.g 1kg" step ="0.01" value="<%= ing['quantity'] %>" name="ingredient[][quantity]" required>
            </div>
          </div>
          <div class="control-group"> 
            <label class="control-label" for="inputEmail">calories per std qty</label>
            <div class="controls">
              <input type="number" name="ingredient[][calories_per_quantity]" step="0.01" required value="<%= ing['calories_per_quantity'] %>" required>
            </div>
          </div>
        </div>
      <%else%>
        <div class="add-ingredient">  
          <div class="control-group">
            <label class="control-label" for="ingredients"><%= ing['name'] %></label> 
             <%= add_remove_ingredient_form_data(@recipe, ing) %> 
              <div class="controls"> 
                <input type="hidden" name="ingredient[][id]" value='<%="#{ing['id']}" %>'>  
                <input type="hidden" name="ingredient[][meal_class]" value='<%="#{ing['meal_class']}" %>'> 
                <input type="hidden" name="ingredient[][std_quantity]" value='<%="#{ing['std_quantity']}" %>'> 
                <input type="hidden" name="ingredient[][calories_per_quantity]" value='<%="#{ing['calories_per_quantity']}" %>'> 
                <input type="hidden" name="ingredient[][name]" value='<%="#{ing['name']}" %>'> 
                <input type="hidden" name="ingredient[][std_measurement]" value='<%="#{ing['std_measurement']}" %>'> 
                <div class="input-append"> 
                  <input placeholder="add-quantity" type="number" step="0.01" name="ingredient[][quantity]" value='<%="#{ing['quantity']}" %>' required>
                  <span class="add-on"><%= ing['std_measurement'] %></span> 
                </div>
              </div> 
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="control-group">
    <div class="controls">
      <button id="add-ingredient" class="btn btn-info btn-small">Add More Ingredient</button>
    </div>
  </div>
  <div id="imageUpload" class="dropzone">
  </div>
  <div class="photo-id">
    <input type="hidden" id="add-photo-array" name="avatar[]" value="">
  </div>
  <br>
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Save Recipe', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

 

app/views/common/_form.html.erb
<!-- @@TODO find dynamic instead of custom url for form-->
<%# form_for("/recipes/#{@recipe.id}", html: { multipart: true , :class => 'form-horizontal'}) do |f| %>

<%= render "/common/images_upload_modal"%>

<%= form_for(@recipe, html: { multipart: true , :class => 'form-horizontal'}) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation" class="control-group">
      <div class="alerts alert-danger">
        <% @recipe.errors.full_messages.each do |msg| %>
          <p class="text-center"><%= msg %></p>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= print_if_notice(notice)%>
  </div>
 
  <div class="control-group">
    <label class="control-label" for="inputEmail">Recipe Name</label>
    <div class="controls">
      <input type="hidden" id="current_user_id">
      <input  type="hidden" name="recipe[aggregate_ratings]" value='<%=0%>'>
      <input class="span8" type="text" id="inputEmail" placeholder="reipe name" name="recipe[name]" value="<%= @recipe.name %>" required>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Discription</label>
    <div class="controls">
      <textarea class="span8" id="recipe-description" name="recipe[description]" cols="30" rows="10"  required></textarea>
    </div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label" for="inputEmail">serves</label>
    <div class="controls">
      <input class="span4" type="number" name="recipe[serves]" placeholder="ex.4" required>
    </div>
  </div>  

  <div class="control-group">
     <div class="controls"> 
      <h5> Type and select ingredients from the list of ingredietns </h5>
     </div>
  </div>

  <% if logged_in? %>
    <div class="control-group inline">
      <label class="control-label">Select existing ingredients</label>
      <div class="controls">
        <select multiple="multiple" id="existing-ingredient-list" class="chosen-select">
          <%= @existing_ingredients_list = get_existing_ingredient_list %>
          <%@existing_ingredients_list.each do |ing| %>
            <option value='<%= "#{ing.id}-#{ing.name}-#{ing.meal_class}-#{ing.std_quantity}-#{ing.calories_per_quantity}-#{ing.std_measurement}"%>' data-ingredient-name ="<%= "#{ing.name}"%>"><%= ing.name %></option>
          <% end %>
        </select>
      </div>
    </div>
  <% end %>

  <!-- <div class="control-group inline">
   <div class="controls">
     <i class="fa fa-hand-o-left fa-3x  "></i>
     <button class="btn btn-info btn-small" id="add-existing-ingredients-block">click to add selected ingredients</button>
   </div> 
  </div>
  -->
  <div id="existing-ingredient-block">
  </div>

  <div class="ingredients-container">
  </div>

 
  <div class="control-group">
    <div class="controls">
      <button id="add-ingredient" class="btn btn-info btn-small">Add More Ingredients</button>
    </div>
  </div>

  <br>
 
  <div id="imageUpload" class="dropzone">
    
  </div>

  <br>
  
  <div class="photo-id">
    <input type="hidden" id="add-photo-array" name="avatar[]" value="">
  </div>
  
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Save Recipe', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>
<script type="text/javascript">
    // $(document).ready(function() {
    //     $('#select-ingredients').multiselect();
    // });
</script>

app/views/common/_form_edit.html.erb
<%= render "/common/images_upload_modal"%>
<%= form_for(@recipe, :html => { :multipart => true , :class => 'form-horizontal'}) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation" class="control-group">
      <div class="alert alert-info">
        <ul>
          <% @recipe.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <%= print_if_notice notice %>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Recipe Name</label>
    <div class="controls">
      <input  type="hidden" name="recipe[aggregate_ratings]" value='<%=0%>'>
      <input class="span8" type="text" id="inputEmail" placeholder="reipe name" name="recipe[name]" value='<%="#{@recipe.name}"%>' required>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Discription</label>
    <div class="controls">
      <textarea id="recipe-description" class="span8" name="recipe[description]" cols="30" rows="10" value="" required>
        <%= "#{@recipe.description }"%>
      </textarea>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputEmail">serves</label>
    <div class="controls">
      <input class="span4" type="number" name="recipe[serves]" placeholder="4" required value="<%= @recipe.serves %>" required>
    </div>
  </div>  
  <div class="control-group">
    <div class="controls">
       <h5>Type and select ingredients from the list of ingredietnss</h5>
    </div>
  </div>
  
  <div class="control-group inline">
    <label class="control-label">Select existing ingredients</label>
    <div class="controls">
      <select multiple="multiple" id="existing-ingredient-list" class="chosen-select">
      <%= @existing_ingredients_list = get_existing_ingredient_list %>
      <% @existing_ingredients_list.each do |ing| %>
        <option value='<%= "#{ing.id}-#{ing.name}-#{ing.meal_class}-#{ing.std_quantity}-#{ing.calories_per_quantity}-#{ing.std_measurement}"%>' data-ingredient-name ="<%= "#{ing.name}"%>"><%= ing.name %></option>
        <% end %>
      </select>
    </div>
  </div>

  
  <div id="existing-ingredient-block">
    
  </div>
 
  <div class="ingredients-container">
    
      <% @recipe.ingredients.each_with_index do |ing, index| 
          if (ing.creator_id == current_user.id)&& (ing.approved == false) %>
       
            <div class="my-existing-ingredient" >
              <hr>
              <button type="button" class="close remove-my-existing-ingredient" data-rec-id='<%= "#{@recipe.id}" %>' data-ing-id ='<%= "#{ing.id}" %>'>&times;</button> 
              <div class="control-group">
                <label class="control-label" for="inputEmail" >ingredient name</label>
                <div class="controls">

                  <input type="hidden"  name="ingredient[][ingredient_id]" value="<%= ing.id %>" required>
                  <input class="span8" type="text" placeholder="ingredient name" value="<%= ing.name %>"  name="ingredient[][name]" required>
                  <input type="hidden"  name="ingredient[][creator_id]" value="<%= ing.creator_id %>" required>
                </div>
              </div>
              <div class="control-group inline">
                <label class="control-label" for="inputEmail">ingredient standard measurement </label>
                <div class="controls">
                  <select name="ingredient[][std_measurement]">
                    <option value="teaspoon">teaspoon</option>
                    <option value="tablespoon">tablespoon</option>
                    <option value="fluid ounce">ounce</option>
                    <option value="gill">gill</option>
                    <option value="cup">cup</option>
                    <option value="pint">pint</option>
                    <option value="quart">quart</option>
                    <option value="gallon">gallon</option>
                    <option value="ml">milli liter</option>
                    <option value="l">liter</option>
                    <option value="dl">deci liter</option>
                    <option value="pounds">pounds</option>
                    <option value="ounce">ounce</option>
                    <option value="mg">mili grams</option>
                    <option value="g">grams</option>
                    <option value="kg">kilo grams</option>
                    <option value="mm">mili meter</option>
                    <option value="cm">centi meter</option>
                    <option value="m">meter</option>
                    <option value="inch">inch</option>
                  </select>
                </div>
              </div>
              <div class="control-group inline">
                  <label class="control-label" for="inputEmail">ingredient meal class </label>
                  <div class="controls">
                    <select name="ingredient[][meal_class]">
                      <option value="jain">jain</option>
                      <option value="veg">veg</option>
                      <option value="non-veg">non-veg</option>
                    </select>
                  </div>
              </div>
              <div class="control-group inline">
                <label class="control-label" for="inputEmail">ingredient standard quantity</label>
                <div class="controls">
                  <input type="number" placeholder="example 10 grams" value="<%= ing.std_quantity %>" name="ingredient[][std_quantity]" required>
                </div>
              </div>
              <div class="control-group inline">
                <label class="control-label" for="inputEmail">ingredient quantity</label>
                <div class="controls">
                  <input type="number" palceholder="e.g 1kg" value="<%= @recipe.recipe_ingredients[index].quantity %>" name="ingredient[][quantity]" required>
                </div>
              </div>
              <div class="control-group"> 
                <label class="control-label" for="inputEmail">calories per std qty</label>
                <div class="controls">
                  <input type="number" name="ingredient[][calories_per_quantity]" required value="<%= ing.calories_per_quantity %>" required>
                </div>
              </div>
            </div>
          <%else%>

          <div class="control-group existing-ingredient">
            <hr>
            <label class="control-label" for="inputEmail" > <%= ing.name %> already exists</label>
            <div class="controls">
              <div class="input-append">
                <input  type="number" placeholder="edit quantity"  value="<%= @recipe.recipe_ingredients[index].quantity %>"  name="existing_ingredient[][quantity]" required>
                <span class="add-on"> <%= ing.std_measurement%> </span>
              </div>
              <input type="hidden"  name="existing_ingredient[][ingredient_id]" value="<%= ing.id %>" required>
              <input type="hidden"  name="existing_ingredient[][creator_id]" value="<%= ing.creator_id %>" required>
              <input type="hidden"  name="existing_ingredient[][std_quantity]" value="<%= ing.std_quantity %>" required>
              <input type="hidden"  name="existing_ingredient[][calories_per_quantity]" value="<%= ing.calories_per_quantity %>" 
              required>
              <input type="hidden"  name="existing_ingredient[][meal_class]" value="<%= ing.meal_class %>" required>
              <button type="button" data-rec-id='<%= "#{@recipe.id}" %>' data-ing-id ='<%= "#{ing.id}" %>' class="close remove-existing-ingredient">&times;</button>
            </div>
          </div>          
          <% end %>
      <% end %>
    
  </div>
  
  <div class="control-group">
    <div class="controls">
      <button id="add-ingredient" class="btn btn-info btn-small">Add More Ingredient</button>
    </div>
  </div>

  <div id="imageUpload" class="dropzone">
    
  </div>

   

  <div class="photo-id">
    <input type="hidden" id="add-photo-array" name="avatar[]" value="">
  </div>
  <br>
<!--   <div class="control-group">
    <label class="control-label" for="inputEmail">Upload` image</label>
    <div class="controls">
      <%# file_field_tag "avatar[]", type: :file, multiple: true %>
    </div>
  </div> -->
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Save Recipe', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

 

app/views/common/_images_upload_modal.html.erb
<!-- <div id="photo-upload-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Upload Imgaes</h3>
  </div>
  <div class="modal-body">
    <%# form_for(@photo, html: { multipart: true, class: "dropzone", :id => 'photo-upload'}) do |f|  %>
      <div class="fallback">
        <%# f.file_field :image %><br>
        <%# f.submit "Upload" %>
      </div>
    <% #end %>
  </div>
  <div class="modal-footer">
     
    
  </div>
</div>
 -->

app/views/common/_latest_feeds.html.erb
 <% @recipe_list.each do |rec| %>
  <div class="image-div">
    <a class="thumbnail" href="#">
  		<%= (!rec.photos.empty? ? (image_tag(rec.photos.first.avatar.url(:medium), :class => "media-object, img-rounded", :style=> "width:175px;height:150px")) : image_tag("missing.png", :style => "width:175px;height:150px;")) %>  
    </a>
  </div>
  <div class="media">
    <div class="media-body">
    <div>
      <h4 class="media-heading inline page-header"><%= link_to(rec.name.titlecase, rec, {:class => "list-recipe-name"}) %> </h4>
      <%= print_meal_class(rec.meal_class, 'list') %>
    </div>
      <span><%= print_star_rates(rec.aggregate_ratings) %>  </span>
      <p>
      	<%= rec.description.truncate(60) %>
      </p>
      <strong>created about <%= time_ago_in_words(rec.created_at) %> ago </strong> 
    </div>
  </div>
	<hr>
<% end %>
 

app/views/common/_user_profile_recipes.html.erb
<% @recipe_list||=[] 
	@admin_show_status ||= false
%>
<div class="container navbar-spacer">
	<h3 class="page-header"> <%= "#{@page_header}" %></h3>
	<%= render  '/common/rate_modal' %>
	<div id="display-notice-message">
		<% if notice %>
			<div class="alert alert-info">
				<%= notice %>
			</div>
		<% end %>
	</div>
 
<% @recipe_list.each_slice(3) do |rec_block| %>
	
	<div class="row">
	<% rec_block.each do |rec| %>
		<div class="span4">
			<ul class="thumbnails">
			  <li class="span4">
			    <div class="thumbnail">
			      	<%= (!rec.photos.empty? ? (image_tag(rec.photos.first.avatar.url(:medium), :class => "media-object, img-rounded", :style=> "")) : image_tag("missing.png", :style => "")) %> 
			      <h3><%= link_to(rec.name.titlecase, rec, {:class => "list-recipe-name"}) %></h3>
			      <div class="recipe-thumbnail-content">
			      	<%= print_star_rates(rec.aggregate_ratings) %>
			      	<%= print_meal_class(rec.meal_class, 'list') %>
			      	<span class="recipe-date">	<%= rec.created_at.strftime("%D") %> </span> 
			      </div>
			      <p><%=raw rec.description.truncate(60) %></p> 
			       
			      <%= link_to("view", rec, {:class => "btn btn-primary"}) %>
			       
			    </div>
			  </li>
			</ul>
		</div>
	<% end %>
	</div>
<% end %>
	<div class="row">
		<div class="span12">
			<div class="pagination pagination-large">
				<%= will_paginate @recipe_list, renderer: BootstrapPagination::Rails if !@recipe_list.empty? %>
			</div>
		</div>
	</div>
</div>


 

app/views/common/_user_specific_recipe_data.html.erb
<% if logged_in? %>
	<% if @recipe.creator_id != @current_user.id %>
		<a href="#" class="btn btn-primary btn-large rate-recipe" data-rec-id="<%= @recipe.id %>">Rate This Recipe </a>
	<%end%>
	<% if @recipe.creator_id == @current_user.id%>	
		<%# link_to("", {:controller => :recipes, :action => :edit, :id => @recipe.id} ,{:class => "fa fa-pencil fa-3x edit-recipe"})%>
		<%= link_to("", edit_recipe_path , :class => "fa fa-pencil fa-3x edit") %>
	<% end %>
<% end %>

app/views/common/create_recipe.html.erb
<!-- <h1>Create New Recipe </h1> -->
<div class="container navbar-spacer">
  <div class="row">
    <div class="span12">
      <!-- <div class="well"> -->
      <div class="page-header">
        <h3>Add New Recipe</h3>
      </div>
        <div class="recipe-form-container">
          <%= render '/common/common_form' %>
        </div>
     <!--  </div> -->
    </div>
  </div>
</div>

<% #link_to 'Back', recipes_path %>

app/views/common/edit_recipe.html.erb
<div class="container navbar-spacer">
	<div class="row">
		<div class="span12">
			<div class="page-header">
				<h3>Edit <%= @recipe.name %></h3>
			</div>
			<div class="recipe-form-container">
				<%= render '/common/common_form' %>
			</div>
		</div>
	</div>
</div>

app/views/common/rated_users_list.html.erb
<div class="container navbar-spacer">
	<div class="row">
		<div class="span12">
			  <% @users_list.each do |item| %>
					<div class="panel panel-default">
			      <div class="panel-heading">
			        <h4 class="panel-title"><%= link_to(item.rater.name, ("/users/"+item.rater.id.to_s),{:class => "inline"}) %></h4>
			      </div>
			      <div class="panel-body">
			      	<div class="user-info" style="padding-left:30%">
				      	<div class="inline">	
				        	<img src='<%= item.rater.avatar.url(:thumb) %>' class="media-object inline" style="width:35px;" />
				      	</div>
				      	<div class="inline" style="padding-left:30px;">
				        	<%= item.rater.email %>
				      	</div>
			      	</div>
			      </div>
					</div>
				<% end %>
		</div>
	</div>
</div>

app/views/common/search.html.erb
<section>
	<div class="container navbar-spacer">
		<div class="row">
			<div class="span12">
				<div class="search-container">
					<form method="post" action="/search" class="form-inline">
							<input name="flag[recipe]" type="text" value="" class="input-small span3" placeholder="free-text">
							<input class="input-small" placeholder="ingredients" type="text" name="flag[ingredients]">
  						<input class="input-small" type="number" name="flag[aggregate_ratings]" placeholder="aggregate ratings" value="">
							<input class="input-small span2" placeholder="calories-from" type="number" name="flag[calories][]">
							<input class="input-small span2" placeholder="calories-to" type="number" name="flag[calories][]">
							<select name="flag[meal_class]"> 
								<option value="">meal class</option>
								<option value="jain">jain</option> 
								<option value="veg">veg</option>
								<option value="non-veg">non-veg</option>
							</select>		 
							<button type="submit" class="btn"><i class="fa fa-search"></i></button>
							<div id="slider-range"></div>
					</form>
				</div>
			</div>
 

		</div>
	</div>


</section>
<section>
	 <%= render :template => '/common/recipe_list' %>
</section>

app/views/common/user_profile.html.erb
<!-- <div class="container navbar-spacer"> -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <div class="fb-profile">
    <img align="left" class="fb-image-lg" src="<%= @user.cover.url(:cover_size) %>" alt="Profile image example"/>
    <img align="left" src='<%= @user.avatar.url() %>' class="fb-image-profile img-circle" alt="profile image" />
    <!-- <img  class="" src="http://lorempixel.com/180/180/people/9/" /> -->
    <div class="fb-profile-text inline">
      <h1><%= @user.name %></h1>
      <h5>Total Recipes <%= "#{@recipe_list.count}" %></h5>
    </div>

    <%= print_user_profile_edit_link(@user)%>
  </div>
  <%= render '/common/user_profile_recipes' %>
 

 

app/views/common/xx_user_specific_recipe_data.html.erb
<% if logged_in? %>
	<% if @recipe.creator_id != @current_user.id %>
		<a href="#" class="btn btn-primary btn-large rate-recipe" data-rec-id="<%= @recipe.id %>">Rate This Recipe </a>
	<%end%>
	<% if @recipe.creator_id == @current_user.id%>	
		<%# link_to("", {:controller => :recipes, :action => :edit, :id => @recipe.id} ,{:class => "fa fa-pencil fa-3x edit-recipe"})%>
		<%= link_to("", edit_recipe_path , :class => "fa fa-pencil fa-3x edit") %>
	<% end %>
<% end %>