config/routes.rb
Foodholic::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_for :users
  root :to => 'home#index' 
  
  

  devise_scope :user do
    match '/user/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session, via: [:get, :delete]
  end
  
 

  
  
  scope :module => "recipe"   do
    get '/search' => 'recipes#search' , :via => :get, :as => 'search_recipes'
    post '/search' => 'recipes#search_recipes', :as => 'search_by_click'
    get '/recipes/:id/:ratings/rated_users' => 'recipes#rated_users_list', :as => 'rated_users_list' 
    get '/recipes/top_rated_recipes' => 'recipes#top_rated_recipes', :as => "top_rated_recipes"
    get '/recipes/most_rated_recipes'=> 'recipes#most_rated_recipes', :as => "most_rated_recipes"

    
    put '/recipes/approve_recipe' => 'admin_recipes#approve_recipe', :as => 'approve_recipe'
    put '/recipes/reject_recipe' => 'admin_recipes#reject_recipe', :as => "reject_recipe"
    get '/recipes/admin_pending_recipes' => 'admin_recipes#admin_pending_recipes', :as => 'admin_pending_recipes' 

    get '/recipes/new' => 'user_recipes#new',  :as => 'new_recipe'   
    post '/recipes/rate' => 'user_recipes#rate_recipe'
    get '/recipes/my_pending_recipes' => 'user_recipes#my_pending_recipes', :as => "my_pending_recipes"
    get '/recipes/my_rejected_recipes' => 'user_recipes#my_rejected_recipes', :as => "my_rejected_recipes"
    get '/recipes/my_top_rated_recipes' => 'user_recipes#my_top_rated_recipes', :as => "my_top_rated_recipes"
    get '/recipes/my_most_rated_recipes' => 'user_recipes#my_most_rated_recipes', :as => "my_most_rated_recipes"
    get '/recipes/my_approved_recipes' => 'user_recipes#my_approved_recipes', :as => "my_approved_recipes"
    get '/recipes/:id/edit' => 'user_recipes#edit' , :as => 'edit_recipe'
    put '/recipes/:id' => 'user_recipes#update'
    post '/recipes' => 'user_recipes#create'
    get '/recipes' => 'user_recipes#index'
    delete '/recipes/destroy_ingredient' => "user_recipes#destroy_ingredient"
    get '/recipes/:id' => 'recipes#show' ,:as => 'recipe'
  end
  

  get '/users/:id' => 'users#show' ,:as => 'user'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  
  put '/users/:id' => 'users#update' 
  get  'photos(.:format)' => 'photos#index', :as => :photos
  post '/photos(.:format)' => 'photos#create'
  get  '/photos/new(.:format)' => 'photos#new', :as => :new_photo
  get  '/photos/:id/edit(.:format)' => 'photos#edit', :as => :edit_photo
  get  '/photos/:id(.:format)' => 'photos#show', :as => :photo 
  put  '/photos/:id(.:format)' => 'photos#update'
  delete '/photos/:id(.:format)' => 'photos#destroy'
                            

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse fixed-navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Foodholic</a>
      <div class="nav-collapse collapse navbar-responsive-collapse">
        <ul class="nav">
          <%= print_admin_pending_recipe_link %>
          <li> <%= link_to("Top Rated Recipes", top_rated_recipes_path) %></li>
          <li><%= link_to("Most Rated Recipes", most_rated_recipes_path) %></li>
          <li><%= link_to("Search", search_recipes_path)%></li>
          <li><%= link_to 'Create Recipe', new_recipe_path %></li>
          <%= print_user_recipes_navbar_links %>
        </ul>
        <ul class="nav pull-right">
          <%= print_user_profile_navbar_links %>
          <%= print_login_link %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div>
  </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodholic</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body> 
<p>new start</p>
<%=render :partial => 'layouts/header'  %>
<%= yield %>
</body>
</html>

app/views/layouts/before_login_header.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Foodholic</a>
      <div class="nav-collapse collapse navbar-responsive-collapse">
        <ul class="nav">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="#">My Recipes</a></li>
          <li><%= link_to 'Create Recipe', new_recipe_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li class="nav-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-search pull-left" action="">
          <input type="text" class="search-query span2" placeholder="Search">
        </form>
        <ul class="nav pull-right">
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li> 
        </ul>
      </div><!-- /.nav-collapse -->
    </div>
  </div> 
</div>